# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: 夏钒曾的个人主页  # 修改此处
  params:
    description: 夏钒曾的个人主页
  menu:
    main:
      - name: 首页
        url: '#about'
        weight: 10

      - name: 新闻
        url: '#news'
        weight: 20

      - name: 工作经历  # 修改：原为“经验”
        url: '#experience'
        weight: 30

      # 删除：项目 (Project) 这一栏

      - name: 论文项目  # 修改：原为“论文”
        url: '#publications'
        weight: 50

      - name: 其他任职  # 修改：原为“服务”
        url: '#service'
        weight: 60
